# Polypy

## Tutorial 1 - Reading data

### DLPOLY

The first thing to do with polypy is to read the data, whether it be in the DL_POLY HISTORY or CONFIG format. Polypy will read these formats and return a dictionary

 ```
data = {'label': Unique atom names, 
        'trajectories': Atomic trajectories, 
        'lv':Lattice vectors, 
        'timesteps':Total number of timesteps, 
        'natoms': Total number of atoms}
```

### HISTORY Files

In [1]:
from polypy import read as rd
import numpy as np

In [2]:
#history = rd.read_history("../example_data/HISTORY", ["CA", "F"])
history = rd.History("../example_data/HISTORY", ["CA", "F"])

In [3]:
print(history.trajectory)

In [4]:
print(history.trajectory.fractional_trajectory)

[[0.5170937  0.51658126 0.51643485]
 [0.51658126 0.61669107 0.61654466]
 [0.61669107 0.51658126 0.61691069]
 ...
 [0.46866197 0.25395423 0.58485915]
 [0.37035211 0.58795775 0.45221831]
 [0.36552817 0.48637324 0.17484859]]


In [5]:
config_1 = history.trajectory.get_atom("CA")

print(config_1.fractional_trajectory)

[[0.5170937  0.51658126 0.51643485]
 [0.51658126 0.61669107 0.61654466]
 [0.61669107 0.51658126 0.61691069]
 ...
 [0.31458099 0.41869718 0.41764085]
 [0.42742958 0.32461268 0.42507042]
 [0.42485915 0.42183099 0.31564789]]


polypy returns an (timesteps * number of atoms) x 3 array containing the atomic coordinates of all selected atoms at all timesteps. It is possible to isolate the CONFIG at a specified timestep using the get_config function.

In [6]:

config = rd.Config("../example_data/CONFIG", ["F"])

print(config)

In [7]:
config_1 = config.trajectory.get_atom("F")

ValueError: Only one atom type was found

In [ ]:
config_1 = config.trajectory.get_config(1)

In [ ]:
trajectory_1 = rd.get_trajectory(history, 1)

The total number of timesteps are returned as well as the total number of atoms.

In [ ]:
print(history['timesteps'])
print(history['natoms'])

For things like mean squared displacements and particle densities it is neccesary to split the trajectories for each species up into individual objects e.g. An MSD for just the F atoms. This is done by the get_atom function. 

In [ ]:
f_data = rd.get_atom(history, "F")

In [ ]:
print(f_data['timesteps'])
print(f_data['natoms'])

Finally, it is possible to isolate the coordinates of a specific timestep in the HISTORY trajectory. 

In [ ]:
first_config = rd.get_config(history, 1)

In [ ]:
print(first_config)

### CONFIG Files

It is also possible to read CONFIG files and split the data into individual species as with the history file. 

In [ ]:
config = rd.read_config("../example_data/CONFIG", ["CA", "F"])

print(config['timesteps'])
print(config['natoms'])

In [ ]:
f_data = rd.get_atom(config, "F")
print(f_data['timesteps'])
print(f_data['natoms'])

### DLMONTE

In [ ]:
archive = rd.read_archive("../example_data/ARCHIVE", ["CE", "O"])

print(archive['timesteps'])
print(archive['natoms'])