# Polypy

## Tutorial 1 - Reading data

### DLPOLY

The first thing to do with polypy is to read the data, whether it be in the DL_POLY HISTORY or CONFIG format. Polypy will read these formats and return a dictionary

 ```
data = {'label': Unique atom names, 
        'trajectories': Atomic trajectories, 
        'lv':Lattice vectors, 
        'timesteps':Total number of timesteps, 
        'natoms': Total number of atoms}
```

### HISTORY Files

In [1]:
from polypy import read as rd
import numpy as np

In [2]:
#history = rd.read_history("../example_data/HISTORY", ["CA", "F"])
history = rd.read_history("../../../../OLD/data/HISTORY_F", ["BR"])

In [3]:
print(history['label'])

['BR' 'BR' 'BR' ... 'BR' 'BR' 'BR']


polypy returns an (timesteps * number of atoms) x 3 array containing the atomic coordinates of all selected atoms at all timesteps. It is possible to isolate the CONFIG at a specified timestep using the get_config function.

In [4]:
print(history['trajectories'].size)
print(history['trajectories'].shape)

config_1 = rd.get_config(history, timestep=0)

print(config_1)

8742
(2914, 3)
[[-11.829  -6.375 -11.846]
 [ 10.009  12.756  10.007]]


In [5]:
trajectory_1 = rd.get_trajectory(history, 1)

[[[-11.829   -6.375  -11.846 ]
  [ 10.009   12.756   10.007 ]]

 [[-11.789   -6.4175 -12.268 ]
  [ 10.48    13.257    9.5174]]

 [[-11.941   -6.3659 -11.709 ]
  [  9.8873  13.251   10.617 ]]

 ...

 [[ -6.4028  -4.1378  10.362 ]
  [ -7.2466  13.104   -8.047 ]]

 [[ -6.5269  -3.7841   9.8862]
  [ -6.7908  13.916   -6.3647]]

 [[ -6.8095  -3.1214  10.059 ]
  [ -7.1101  13.738   -6.5052]]]
[[10.009  12.756  10.007 ]
 [10.48   13.257   9.5174]
 [ 9.8873 13.251  10.617 ]
 ...
 [-7.2466 13.104  -8.047 ]
 [-6.7908 13.916  -6.3647]
 [-7.1101 13.738  -6.5052]]


The total number of timesteps are returned as well as the total number of atoms.

In [6]:
print(history['timesteps'])
print(history['natoms'])

1457
2


For things like mean squared displacements and particle densities it is neccesary to split the trajectories for each species up into individual objects e.g. An MSD for just the F atoms. This is done by the get_atom function. 

In [7]:
f_data = rd.get_atom(history, "F")

In [8]:
print(f_data['timesteps'])
print(f_data['natoms'])

1457
2


Finally, it is possible to isolate the coordinates of a specific timestep in the HISTORY trajectory. 

In [9]:
first_config = rd.get_config(history, 1)

In [10]:
print(first_config)

[[-11.789   -6.4175 -12.268 ]
 [ 10.48    13.257    9.5174]]


### CONFIG Files

It is also possible to read CONFIG files and split the data into individual species as with the history file. 

In [11]:
config = rd.read_config("../example_data/CONFIG", ["CA", "F"])

print(config['timesteps'])
print(config['natoms'])

[[27.32  0.    0.  ]
 [ 0.   27.32  0.  ]
 [ 0.    0.   27.32]]
1
1500


In [12]:
f_data = rd.get_atom(config, "F")
print(f_data['timesteps'])
print(f_data['natoms'])

KeyError: 'frac_trajectories'

### DLMONTE

In [ ]:
archive = rd.read_archive("../example_data/ARCHIVE", ["CE", "O"])

print(archive['timesteps'])
print(archive['natoms'])