# Polypy

### Tutorial 1 - Reading data

The first thing to do with polypy is to read the data, whether it be in the DL_POLY HISTORY/CONFIG format, or in the DL_MONTE ARCHIVE format. Polypy will read these formats and return a dictionary

 ```
data = {'label': Unique atom names, 
        'trajectories': Atomic trajectories, 
        'lv':Lattice vectors, 
        'timesteps':Total number of timesteps, 
        'natoms': Total number of atoms}
```

In [1]:
from polypy import read as rd
import numpy as np

In [2]:
history = rd.read_history("example_data/HISTORY", ["CA", "F"])

In [4]:
print(history['label'])

['CA' 'CA' 'CA' ... 'F' 'F' 'F']


polypy returns an (timesteps * number of atoms) x 3 array containing the atomic coordinates of all selected atoms at all timesteps. 

In [5]:
print(history['trajectories'])

[[-13.193  -13.207  -13.211 ]
 [-13.207  -10.472  -10.476 ]
 [-10.472  -13.207  -10.466 ]
 ...
 [-13.885   12.04   -13.591 ]
 [ 12.996   10.124    7.5745]
 [ 11.166   13.706    9.6046]]


In [6]:
print(history['lv'])

[[27.32 27.32 27.32]
 [27.36 27.36 27.36]
 [27.4  27.4  27.4 ]
 [27.44 27.44 27.44]
 [27.48 27.48 27.48]
 [27.51 27.51 27.51]
 [27.54 27.54 27.54]
 [27.58 27.58 27.58]
 [27.6  27.6  27.6 ]
 [27.63 27.63 27.63]
 [27.66 27.66 27.66]
 [27.68 27.68 27.68]
 [27.71 27.71 27.71]
 [27.73 27.73 27.73]
 [27.76 27.76 27.76]
 [27.78 27.78 27.78]
 [27.8  27.8  27.8 ]
 [27.82 27.82 27.82]
 [27.84 27.84 27.84]
 [27.86 27.86 27.86]
 [27.87 27.87 27.87]
 [27.89 27.89 27.89]
 [27.91 27.91 27.91]
 [27.92 27.92 27.92]
 [27.94 27.94 27.94]
 [27.95 27.95 27.95]
 [27.97 27.97 27.97]
 [27.98 27.98 27.98]
 [27.99 27.99 27.99]
 [28.01 28.01 28.01]
 [28.02 28.02 28.02]
 [28.03 28.03 28.03]
 [28.04 28.04 28.04]
 [28.05 28.05 28.05]
 [28.06 28.06 28.06]
 [28.07 28.07 28.07]
 [28.08 28.08 28.08]
 [28.09 28.09 28.09]
 [28.1  28.1  28.1 ]
 [28.11 28.11 28.11]
 [28.12 28.12 28.12]
 [28.12 28.12 28.12]
 [28.13 28.13 28.13]
 [28.14 28.14 28.14]
 [28.15 28.15 28.15]
 [28.15 28.15 28.15]
 [28.16 28.16 28.16]
 [28.17 28.17

In [8]:
print(history['timesteps'])

100


In [9]:
print(history['natoms'])

1500


In [3]:
ca_data = rd.get_atom(data, "U")

In [4]:
f_data = rd.get_atom(data, "O")

In [5]:
ca_data = rd.read_history("HIST", ["U"])
f_data = rd.read_history("HIST", ["O"])

No Atoms of specified type exist within the selected HISTORY file


SystemExit: 0

/home/adam/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2889: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
