In [1]:
import numpy as np
from numpy import linalg as la
import pandas as pd

x = np.array([[[5, 0, 0],
              [0, 5, 0],
              [0, 0, 5]], 
              [[27, 0, 0],
              [0, 27, 0],
              [0, 0,276]]])

print(x[1][0,:])

[27  0  0]


In [2]:
z = np.array([5, 5, 5])

x = np.array([[0.000, 32.87, 0.000],    
              [0.000, 10.96, 33.57],    
              [105.2, 0.9000E-09, -3.216]])

y = np.array([[105.2, 0.9000E-09, -3.216],
              [0.000, 32.87, 0.000],    
              [0.000, 10.96, 33.57]])

x2 = la.inv(np.transpose(x))
y2 = la.inv(np.transpose(y))

print(x2)
print(y2)

z1 = np.matmul(x2, z) 
z1 = np.mod(z1, 1)
z2 = np.matmul(y2, z)
z2 = np.mod(z2, 1)

print(z1)
print(z2)

[[-0.00030364  0.03042288 -0.00993252]
 [ 0.00091064  0.          0.0297885 ]
 [ 0.0095057   0.          0.        ]]
[[ 0.0095057   0.          0.        ]
 [-0.00030364  0.03042288 -0.00993252]
 [ 0.00091064  0.          0.0297885 ]]
[0.10093358 0.15349573 0.04752852]
[0.04752852 0.10093358 0.15349573]


In [3]:
y = [[0, 20, 0], [0, 0, 20]]

y.insert(0, [20, 0, 0])

print(y)

[[20, 0, 0], [0, 20, 0], [0, 0, 20]]


In [7]:
x = np.array([1, 2, 3, 4, 5, 5, 4, 3, 2, 1])

print(x[:5])

print(np.unique(x, return_counts=True))

y = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])


xy = np.column_stack((x, y))
print(xy)

[1 2 3 4 5]
(array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 2]))
[[ 1 10]
 [ 2  9]
 [ 3  8]
 [ 4  7]
 [ 5  6]
 [ 5  5]
 [ 4  4]
 [ 3  3]
 [ 2  2]
 [ 1  1]]


In [5]:
z = pd.DataFrame(xy).groupby(0, as_index=False)[1].mean().values
print(z)

[[1.  5.5]
 [2.  5.5]
 [3.  5.5]
 [4.  5.5]
 [5.  5.5]]
