In [1]:
from polypy import read_dl_poly as dlpy
from polypy import read_dl_monte as dlmt
from polypy import read_utils as rd_ut
from polypy import read as rd
import numpy as np
import os
from polypy import trajectory

In [2]:
traj_monte = dlmt.read_trajectory("../example_data/ARCHIVE")

traj_obj = trajectory.PolyTrajectory(traj_monte)

Read trajectory with 100 configurations


In [3]:
print(traj_obj.get_file_type())

DLMONTE


In [4]:
print(traj_obj.get_nconfigs())

100


In [5]:
print(traj_obj.get_title())

No title in a DLMONTE file
None


In [6]:
print(traj_obj.get_style())

No style in a DLMONTE file
None


In [7]:
print(traj_obj.get_total_natoms())

Atom number does not change
8640.0


In [8]:
print(traj_obj.lattice_vectors())

[[164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1        21.88       32.82     ]
 [164.1000397  21.8800053  32.8200079]
 [164.1000397  21.8800053

In [9]:
print(traj_obj.atom_coordinates("CE"))

[[-81.5941667 -10.4841667 -15.9541667   0.       ]
 [-81.5941667  -7.7491667 -13.2191667   0.       ]
 [-78.8591667 -10.4841667 -13.2191667   0.       ]
 ...
 [ 77.0358155   8.6608313  14.1308301   0.       ]
 [ 79.7708149   5.925832   14.1308301   0.       ]
 [ 79.7708149   8.6608313  11.3958307   0.       ]]


In [10]:
print(traj_obj.get_natoms("CE"))


2880


In [11]:
#print(len(traj_monte))
#print(traj_monte[0]['title'])
#print(traj_monte[0]['style'])
#print(traj_monte[0]['lvs'])
#print(traj_monte[0]['nummols'])
#print(traj_monte[0]['moltypes'])
#print(traj_monte[0]['maxmols'])

#for i in range(traj_monte[0]['nummols']):
#    print(traj_monte[0]['mols'][i]['name'])
 #   print(traj_monte[0]['mols'][i]['numatoms'])
  #  print(traj_monte[0]['mols'][i]['maxatoms'])

   # for j in range(0, traj_monte[0]['mols'][i]['maxatoms']):
    #    print(traj_monte[0]['mols'][i]['atoms'][j])

In [12]:
traj = dlpy.read_trajectory("../example_data/HISTORY")

traj_obj = trajectory.PolyTrajectory(traj)

lvs = traj_obj.lattice_vectors()

Read trajectory with 500 configurations


In [13]:
print(lvs)
print(traj_obj.get_file_type())

[[27.32 27.32 27.32]
 [27.36 27.36 27.36]
 [28.8  28.8  28.8 ]
 ...
 [28.47 28.47 28.47]
 [28.35 28.35 28.35]
 [28.4  28.4  28.4 ]]
DLPOLY


In [14]:
print(traj_obj.timestep())

0.1


In [15]:
nconfigs = traj_obj.get_nconfigs()

In [16]:
print(traj_obj.get_title())
print(traj_obj.get_style())

surfa_______________:       0.0000000000     0.0000000000    27.3200000000      
[   0    3 1500]


In [17]:
natoms = traj_obj.get_total_natoms()
print(natoms)

1500


In [19]:
f_coords = traj_obj.atom_coordinates("F")
#print(f_coords.shape)
print(f_coords)

[array([[-3.639 ,  7.296 , -3.6394],
       [-6.3635,  7.2868, -3.6393],
       [-3.6363,  4.5596, -6.3786],
       ...,
       [10.014 , 12.748 , 12.745 ],
       [12.749 , 10.025 , 10.014 ],
       [10.009 , 12.756 , 10.007 ]]), array([[-3.6232,  7.4233, -3.5274],
       [-6.1555,  7.2409, -3.58  ],
       [-3.4525,  4.3159, -6.0674],
       ...,
       [10.792 , 12.305 , 12.34  ],
       [12.476 , 10.36  , 10.914 ],
       [ 9.9435, 13.491 , 10.097 ]]), array([[-3.2599,  7.9166, -3.2791],
       [-6.5302,  8.6967, -4.1258],
       [-3.9167,  4.2   , -6.1961],
       ...,
       [10.658 , 13.354 , 13.453 ],
       [13.581 , 10.811 , 10.293 ],
       [11.089 , 13.641 , 10.437 ]]), array([[-3.7358,  7.5035, -3.6574],
       [-6.986 ,  7.8536, -4.0819],
       [-3.8971,  4.3062, -6.2496],
       ...,
       [10.144 , 12.882 , 13.526 ],
       [13.117 , 10.498 , 10.315 ],
       [11.237 , 14.063 ,  9.7633]]), array([[-4.2091,  7.518 , -4.5553],
       [-6.5512,  7.4624, -3.853 ],
       

In [ ]:
f_atoms = traj_obj.get_natoms("F")
print(f_atoms)

In [ ]:
print(f_coords.size / nconfigs)

In [ ]:
print(traj_monte['style'])