In [1]:
import numpy as np
from numpy import linalg as la
import pandas as pd

x = np.array([[[5, 0, 0],
              [0, 5, 0],
              [0, 0, 5]], 
              [[27, 0, 0],
              [0, 27, 0],
              [0, 0,276]]])

print(x[1][0,:])

[27  0  0]


In [2]:
z = np.array([5, 5, 5])

x = np.array([[0.000, 32.87, 0.000],    
              [0.000, 10.96, 33.57],    
              [105.2, 0.9000E-09, -3.216]])

y = np.array([[105.2, 0.9000E-09, -3.216],
              [0.000, 32.87, 0.000],    
              [0.000, 10.96, 33.57]])

x2 = la.inv(np.transpose(x))
y2 = la.inv(np.transpose(y))

print(x2)
print(y2)

z1 = np.matmul(x2, z) 
z1 = np.mod(z1, 1)
z2 = np.matmul(y2, z)
z2 = np.mod(z2, 1)

print(z1)
print(z2)

[[-0.00030364  0.03042288 -0.00993252]
 [ 0.00091064  0.          0.0297885 ]
 [ 0.0095057   0.          0.        ]]
[[ 0.0095057   0.          0.        ]
 [-0.00030364  0.03042288 -0.00993252]
 [ 0.00091064  0.          0.0297885 ]]
[0.10093358 0.15349573 0.04752852]
[0.04752852 0.10093358 0.15349573]


In [3]:
y = [[0, 20, 0], [0, 0, 20]]

y.insert(0, [20, 0, 0])

print(y)

[[20, 0, 0], [0, 20, 0], [0, 0, 20]]


In [26]:
x = np.array([1, 1, 1, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10])
y = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

xy = np.column_stack((x, y))

z = pd.DataFrame(xy)

print(z)

     0   1
0    1   1
1    1   2
2    1   3
3    2   4
4    3   5
5    3   6
6    4   7
7    4   8
8    5   9
9    5  10
10   6  11
11   6  12
12   7  13
13   7  14
14   8  15
15   8  16
16   9  17
17   9  18
18  10  19
19  10  20


In [28]:
z1 = z.groupby(0, as_index=False).mean()
z2 = z.groupby(0, as_index=False).sem()

print(z1)
print(z2)

    0     1
0   1   2.0
1   2   4.0
2   3   5.5
3   4   7.5
4   5   9.5
5   6  11.5
6   7  13.5
7   8  15.5
8   9  17.5
9  10  19.5
     0        1
0  1.0  0.57735
1  1.0      NaN
2  1.0  0.50000
3  1.0  0.50000
4  1.0  0.50000
5  1.0  0.50000
6  1.0  0.50000
7  1.0  0.50000
8  1.0  0.50000
9  1.0  0.50000


In [15]:
print(z)

    0   1
0   1  10
1   2   9
2   3   8
3   4   7
4   5   6
5   5   5
6   4   4
7   3   3
8   2   2
9   1   1
10  1  10
11  2   9
12  3   8
13  4   7
14  5   6
15  5   5
16  4   4
17  3   3
18  2   2
19  1   1
